#include "WorkbenchTheme.h"

QString WorkbenchTheme::darkStyleSheet()
{
    return QStringLiteral(
        "QMainWindow, QWidget { background: #0f141a; color: #E8ECF2; font-family: 'IBM Plex Sans Arabic', 'Segoe UI'; }"
        "QFrame[role=\"menuPopup\"] { background: #171B22; color: #E8ECF2; border: 1px solid #303746; }"
        "QPushButton[role=\"menuRow\"] { background: transparent; border: 0; border-radius: 0; padding: 8px 18px; text-align: right; color: #E8ECF2; }"
        "QPushButton[role=\"menuRow\"]:hover { background: #264F78; color: #FFFFFF; }"
        "QWidget#topShell { background: #111318; border-bottom: 1px solid #303746; }"
        "QWidget#topMenuRow { background: #111318; border-bottom: 1px solid #303746; }"
        "QWidget#brandBlock { background: transparent; }"
        "QLabel#brandTextLabel { color: #AEC6FF; font-weight: 600; font-size: 18px; }"
        "QToolButton[role=\"topMenu\"] { background: transparent; border: 1px solid transparent; border-radius: 4px; color: #C8D0DD; font-weight: 600; padding: 7px 10px; }"
        "QToolButton[role=\"topMenu\"]:hover { color: #E8ECF2; background: #202633; border-color: #303746; border-bottom: 2px solid #4C8DFF; }"
        "QToolButton[role=\"topMenu\"]:pressed, QToolButton[role=\"topMenu\"]:checked { color: #A7C4FF; background: #13233A; border-color: #4C8DFF; }"
        "QToolButton[role=\"topMenu\"][active=\"true\"] { color: #A7C4FF; border-bottom: 2px solid #4C8DFF; }"
        "QToolButton[role=\"topMenu\"]::menu-indicator { image: none; width: 0px; }"
        "QToolButton[role=\"primaryAction\"] { background: transparent; border: 1px solid #4C8DFF; border-radius: 12px; padding: 4px 12px; color: #7BDFF2; font-weight: 700; }"
        "QToolButton[role=\"primaryAction\"]:hover { background: #13233A; border-color: #7BDFF2; }"
        "QToolButton { background: #202633; border: 1px solid #303746; border-radius: 4px; padding: 6px 10px; color: #E8ECF2; }"
        "QToolButton:hover { border-color: #4C8DFF; background: #262d3b; }"
        "QToolButton:disabled { color: #6F7A8A; background: #171B22; }"
        "QLineEdit { background: #1B2230; border: 1px solid #303746; border-radius: 12px; padding: 5px 12px; color: #E8ECF2; selection-background-color: #264F78; }"
        "QLineEdit:focus { border-color: #4C8DFF; }"
        "QTreeView, QPlainTextEdit, QListWidget { background: #0D1117; border: 1px solid #303746; selection-background-color: #264F78; color: #E8ECF2; }"
        "QListWidget::item { padding: 8px 10px; border-bottom: 1px solid #1B2230; }"
        "QListWidget::item:hover { background: #13233A; color: #FFFFFF; }"
        "QListWidget::item:selected { background: #264F78; color: #FFFFFF; }"
        "QTabWidget::pane { border: 1px solid #303746; background: #0D1117; }"
        "QTabBar::tab { background: #171B22; color: #A7B0BE; border: 1px solid #303746; padding: 7px 12px; }"
        "QTabBar::tab:selected { background: #202633; color: #E8ECF2; border-top: 2px solid #4C8DFF; }"
        "QDockWidget::title { background: #111318; padding: 6px; text-align: right; color: #E8ECF2; }"
        "QStatusBar { background: #111318; color: #A7B0BE; border-top: 1px solid #303746; }");
}

QString WorkbenchTheme::lightStyleSheet()
{
    return QStringLiteral(
        "QMainWindow, QWidget { background: #F6F7FB; color: #17202A; font-family: 'IBM Plex Sans Arabic', 'Segoe UI'; }"
        "QFrame[role=\"menuPopup\"] { background: #FFFFFF; color: #17202A; border: 1px solid #CCD4E0; }"
        "QPushButton[role=\"menuRow\"] { background: transparent; border: 0; border-radius: 0; padding: 8px 18px; text-align: right; color: #17202A; }"
        "QPushButton[role=\"menuRow\"]:hover { background: #DCEBFF; color: #0C2D57; }"
        "QWidget#topShell { background: #FFFFFF; border-bottom: 1px solid #CCD4E0; }"
        "QWidget#topMenuRow { background: #FFFFFF; border-bottom: 1px solid #CCD4E0; }"
        "QWidget#brandBlock { background: transparent; }"
        "QLabel#brandTextLabel { color: #24589C; font-weight: 600; font-size: 18px; }"
        "QToolButton[role=\"topMenu\"] { background: transparent; border: 1px solid transparent; border-radius: 4px; color: #35465B; font-weight: 600; padding: 7px 10px; }"
        "QToolButton[role=\"topMenu\"]:hover { color: #17202A; background: #EEF4FF; border-color: #CCD4E0; border-bottom: 2px solid #3B74C5; }"
        "QToolButton[role=\"topMenu\"]:pressed, QToolButton[role=\"topMenu\"]:checked { color: #174A8B; background: #DCEBFF; border-color: #3B74C5; }"
        "QToolButton[role=\"topMenu\"][active=\"true\"] { color: #174A8B; border-bottom: 2px solid #3B74C5; }"
        "QToolButton[role=\"topMenu\"]::menu-indicator { image: none; width: 0px; }"
        "QToolButton[role=\"primaryAction\"] { background: #FFFFFF; border: 1px solid #3B74C5; border-radius: 12px; padding: 4px 12px; color: #145C72; font-weight: 700; }"
        "QToolButton[role=\"primaryAction\"]:hover { background: #E4F7FB; border-color: #20869E; }"
        "QToolButton { background: #FFFFFF; border: 1px solid #CCD4E0; border-radius: 4px; padding: 6px 10px; color: #17202A; }"
        "QToolButton:hover { border-color: #3B74C5; background: #EEF4FF; }"
        "QToolButton:disabled { color: #8996A8; background: #EEF1F5; }"
        "QLineEdit { background: #FFFFFF; border: 1px solid #CCD4E0; border-radius: 12px; padding: 5px 12px; color: #17202A; selection-background-color: #B9D5FF; }"
        "QLineEdit:focus { border-color: #3B74C5; }"
        "QTreeView, QPlainTextEdit, QListWidget { background: #FFFFFF; border: 1px solid #CCD4E0; selection-background-color: #B9D5FF; color: #17202A; }"
        "QListWidget::item { padding: 8px 10px; border-bottom: 1px solid #E2E7EF; }"
        "QListWidget::item:hover { background: #EEF4FF; color: #0C2D57; }"
        "QListWidget::item:selected { background: #B9D5FF; color: #0C2D57; }"
        "QTabWidget::pane { border: 1px solid #CCD4E0; background: #FFFFFF; }"
        "QTabBar::tab { background: #EEF1F5; color: #536274; border: 1px solid #CCD4E0; padding: 7px 12px; }"
        "QTabBar::tab:selected { background: #FFFFFF; color: #17202A; border-top: 2px solid #3B74C5; }"
        "QDockWidget::title { background: #FFFFFF; padding: 6px; text-align: right; color: #17202A; }"
        "QStatusBar { background: #FFFFFF; color: #536274; border-top: 1px solid #CCD4E0; }");
}
